<a href="https://colab.research.google.com/github/KUNALP1607/Summer_Internship/blob/main/Basic_Numpy_and_Pandas(Day1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
'''In this example, we are creating a two-dimensional array that has the rank of 2 as it has 2 axes.
The first axis(dimension) is of length 2, i.e., the number of rows, and the second axis(dimension) is of length 3,
i.e., the number of columns. The overall shape of the array can be represented as (2, 3)'''

# Creating array object
arr = np.array( [[ 4, 5, 3],
                 [ 4, 5, 3],
                 [ 8, 7, 2],
                 [ 8, 7, 2]] )

# Printing type of arr object
print("Array is of type: ", type(arr))

# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)

# Printing shape of array
print("Shape of array: ", arr.shape)

# Printing size (total number of elements) of array
print("Size of array: ", arr.size)

# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)


Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (4, 3)
Size of array:  12
Array stores elements of type:  int64


In [12]:
#Python program for Creation of Arrays

import numpy as np

# Creating a rank 1 Array
arr = np.array([3, 2, 4])
print("Array with Rank 1: \n",arr)

# Creating a rank 2 Array
arr = np.array( [[ 4, 5, 3],
                 [ 4, 5, 3],
                 [ 8, 7, 2],
                 [ 8, 7, 2]] )
print("Array with Rank 2: \n", arr)

# Creating an array from tuple
arr = np.array((1, 3, 2))
print("\nArray created using "
      "passed tuple:\n", arr)

Array with Rank 1: 
 [3 2 4]
Array with Rank 2: 
 [[4 5 3]
 [4 5 3]
 [8 7 2]
 [8 7 2]]

Array created using passed tuple:
 [1 3 2]


In [13]:
import numpy as np

# creating array
arr = np.array([5, 4, 9, 10, 3])

# creating copy of array
c = arr.copy()

# both arr and c have different id
print("id of arr", id(arr))
print("id of c", id(c))

# changing original array
# this will not effect copy
arr[0] = 12

# printing array and copy
print("original array- ", arr)
print("copy- ", c)


id of arr 133346013322896
id of c 133346013330384
original array-  [12  4  9 10  3]
copy-  [ 5  4  9 10  3]


In [16]:
# Let's define our function

# Parameters: Input Array
def sum(array):

	# Set variable for our final answer
	sum = 0

	# Parse through our array
	for i in array:

		# Continuously add current element
		# to final sum
		sum += i

	# Return our sum
	return sum

# Create a test array
testArray = [6, 3, 26, 82, 29, 38, 60.3]

# Test our function
print('The sum of your numbers is ' + str(sum(testArray)))


The sum of your numbers is 244.3


In [18]:
import numpy as np

# Create a sequence of integers from 10 to 1 with a step of -2

a = np.arange(11, 1, -3)
print("\n A sequential array with a negative step: \n",a)

# Indexes are specified inside the np.array method.
newarr = a[np.array([3, 1, 2 ])]

print("\n Elements at these indices are:\n",newarr)



 A sequential array with a negative step: 
 [11  8  5  2]

 Elements at these indices are:
 [2 8 5]


In [21]:
#The result includes the start index, but excludes the end index

import numpy as np

arr = np.array([7, 5, 6, 2, 3, 5, 2])

print(arr[1:4])
print(arr[5:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])


[5 6 2]
[5 2]
[7 5 6 2]
[3 5]
[5 2]
[7 6 3 2]


In [27]:
import numpy as np

arr = np.array([[7, 5, 6, 2, 3], [5, 4, 9, 10, 3]])

print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])

[ 4  9 10]
[6 9]
[[ 5  6  2]
 [ 4  9 10]]


In [29]:
#The copy SHOULD NOT be affected by the changes made to the original array.

import numpy as np

arr = np.array([5, 4, 9, 10, 3])
x = arr.copy()
arr[0] = 59

print(arr)
print(x)

[59  4  9 10  3]
[ 5  4  9 10  3]


In [30]:
#The view SHOULD be affected by the changes made to the original array.

import numpy as np

arr = np.array([7, 5, 6, 2, 3, 5, 2])
x = arr.view()
arr[0] = 66

print(arr)
print(x)

[66  5  6  2  3  5  2]
[66  5  6  2  3  5  2]


In [31]:
import numpy as np

arr = np.array([5, 4, 9, 10, 3])
x = arr.view()
x[0] = 72

print(arr)
print(x)

[72  4  9 10  3]
[72  4  9 10  3]


In [34]:
''' Check if Array Owns its Data
copies owns the data, and views does not own the data, but how can we check this?
Every NumPy array has the attribute base that returns None if the array owns the data.
Otherwise, the base  attribute refers to the original object.'''

import numpy as np

arr = np.array([7, 5, 6, 2, 3, 5, 2])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[7 5 6 2 3 5 2]


In [37]:
import numpy as np

arr = np.array([[5, 4, 9, 10, 3], [7, 5, 6, 2, 3]])

#Let's find No. of rows and No. of columns :-
print(arr.shape)


(2, 5)


In [39]:
'''Create an array with 5 dimensions using ndmin
using a vector with values 1,2,3,4 and verify that last dimension has value 4:'''

import numpy as np

arr = np.array([5, 4, 9, 10, 3], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[ 5  4  9 10  3]]]]]
shape of array : (1, 1, 1, 1, 5)


In [41]:
#Convert the following 1-D array with 12 elements into a 2-D array.

#The outermost dimension will have 4 arrays, each with 3 elements:

import numpy as np

arr = np.array([7, 5, 6, 2, 3, 5, 2, 4, 5, 6, 2, 1])

newarr = arr.reshape(4, 3)

print(newarr)

#The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[7 5 6]
 [2 3 5]
 [2 4 5]
 [6 2 1]]
[[[7 5]
  [6 2]
  [3 5]]

 [[2 4]
  [5 6]
  [2 1]]]


In [42]:
# Python code to demonstrate matrix operations
# add(), subtract() and divide()

# importing numpy for matrix operations
import numpy

# initializing matrices
x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])

# using add() to add matrices
print ("The element wise addition of matrix is : ")
print (numpy.add(x,y))

# using subtract() to subtract matrices
print ("The element wise subtraction of matrix is : ")
print (numpy.subtract(x,y))

# using divide() to divide matrices
print ("The element wise division of matrix is : ")
print (numpy.divide(x,y))


The element wise addition of matrix is : 
[[ 8 10]
 [13 15]]
The element wise subtraction of matrix is : 
[[-6 -6]
 [-5 -5]]
The element wise division of matrix is : 
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]


In [43]:
import pandas

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [2, 9, 1]
}

myvar = pandas.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         2
1  Volvo         9
2   Ford         1


In [46]:
#Pandas package can be referred to as pd instead of pandas.
import pandas as pd

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

#pd in behalf of pandas :-
myvar = pd.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [47]:
#The version string is stored under __version__ attribute.

import pandas as pd

print(pd.__version__)

2.0.3


In [48]:
#A Pandas Series is like a column in a table.

#It is a one-dimensional array holding data of any type.
import pandas as pd

a = [3, 5, 1]

myvar = pd.Series(a)

print(myvar)
#If nothing else is specified, the values are labeled with their index number.
#First value has index 0, second value has index 1 etc.
#This label can be used to access a specified value.
#Return the first value of the Series:

print(myvar[0])

0    3
1    5
2    1
dtype: int64
3


In [49]:
import pandas as pd

a = [2, 9, 1]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)

print(myvar["y"])

x    2
y    9
z    1
dtype: int64
9


In [52]:
#A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.

import pandas as pd

data = {
  "calories": [367, 425, 232],
  "duration": [30, 50, 35]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df)


#Pandas use the loc attribute to return one or more specified row(s)
#refer to the row index:
print(df.loc[0])
#Returns a pandas series


#use a list of indexes:
print(df.loc[[0, 1]])
#When using [], the result is a Pandas DataFrame.

   calories  duration
0       367        30
1       425        50
2       232        35
calories    367
duration     30
Name: 0, dtype: int64
   calories  duration
0       367        30
1       425        50


In [61]:
import pandas as pd

df = pd.read_csv('Data_(Day1).csv')

print(df.to_string())
#use to_string() to print the entire DataFrame.

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [62]:
import pandas as pd

print(pd.options.display.max_rows)
#The number of rows returned is defined in Pandas option settings.

#You can check your system's maximum rows with the pd.options.display.max_rows statement.

60


In [63]:
import pandas as pd

pd.options.display.max_rows = 9999

df = pd.read_csv('Data_(Day1).csv')

print(df)

print(pd.options.display.max_rows)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes
9999


In [64]:
#Load a Python Dictionary into a DataFrame   JSON= Python Dictionary
import pandas as pd

data = {
  "Duration":{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60
  },
  "Pulse":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102
  },
  "Maxpulse":{
    "0":130,
    "1":145,
    "2":135,
    "3":175,
    "4":148,
    "5":127
  },
  "Calories":{
    "0":409,
    "1":479,
    "2":340,
    "3":282,
    "4":406,
    "5":300
  }
}

df = pd.DataFrame(data)

print(df)


   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300


In [65]:
# importing the module
import pandas as pd

# creating the first DataFrame
df1 = pd.DataFrame({"fruit" : ["apple", "banana", "avocado"],
					"market_price" : [21, 14, 35]})
display("The first DataFrame")
display(df1)

# creating the second DataFrame
df2 = pd.DataFrame({"fruit" : ["banana", "apple", "avocado"],
					"wholesaler_price" : [65, 68, 75]})
display("The second DataFrame")
display(df2)

# joining the DataFrames
display("The merged DataFrame")
pd.merge(df1, df2, on = "fruit", how = "inner")
# how : {‘left’, ‘right’, ‘outer’, ‘inner’}, default ‘inner’


'The first DataFrame'

fruit  market_price
0    apple            21
1   banana            14
2  avocado            35

'The second DataFrame'

fruit  wholesaler_price
0   banana                65
1    apple                68
2  avocado                75

'The merged DataFrame'

fruit  market_price  wholesaler_price
0    apple            21                68
1   banana            14                65
2  avocado            35                75

In [66]:
#Merging two data frames with different number of elements
# importing the module
import pandas as pd

# creating the first DataFrame
df1 = pd.DataFrame({"fruit" : ["apple", "banana",
                               "avocado", "grape"],
                    "market_price" : [21, 14, 35, 38]})
display("The first DataFrame")
display(df1)

# creating the second DataFrame
df2 = pd.DataFrame({"fruit" : ["apple", "banana", "grape"],
                    "wholesaler_price" : [65, 68, 71]})
display("The second DataFrame")
display(df2)

# joining the DataFrames
# here both common DataFrame elements are in df1 and df2,
# so it extracts apple, banana, grapes from df1 and df2.
display("The merged DataFrame")
pd.merge(df1, df2, on = "fruit", how = "inner")

pd.merge(df1, df2, on = "fruit", how = "outer")

'The first DataFrame'

fruit  market_price
0    apple            21
1   banana            14
2  avocado            35
3    grape            38

'The second DataFrame'

fruit  wholesaler_price
0   apple                65
1  banana                68
2   grape                71

'The merged DataFrame'

fruit  market_price  wholesaler_price
0    apple            21              65.0
1   banana            14              68.0
2  avocado            35               NaN
3    grape            38              71.0

In [74]:
# Pandas dataframe.groupby() function is used to split the data into groups based on some criteria.
# Pandas objects can be split on any of their axes.
# The abstract definition of grouping is to provide a mapping of labels to group names.
# importing pandas as pd
import pandas as pd

# Creating the dataframe
df = pd.read_csv("Data_(Day1).csv")

# Print the dataframe
print(df.head())    #Returns  top n (5 by default) rows of a data frame or series.



   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes


In [76]:
#Indentation
j = 1

while(j<= 5):
	print(j)
	j = j + 1


1
2
3
4
5
